### ISSUE TITLE
NullPointerException in Plugin Android Support

### ISSUE THREAD

**Issue by GlennVM** [LocativeHQ/android-app#39]
When I try to build the app, Android studio quits building the gradle and throws this exception
```
null
java.lang.NullPointerException
	at com.intellij.openapi.util.io.FileUtilRt.toSystemIndependentName(FileUtilRt.java:207)
	at com.intellij.openapi.util.io.FileUtil.toSystemIndependentName(FileUtil.java:634)
	at org.jetbrains.android.sdk.AndroidTargetData$1.run(AndroidTargetData.java:99)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:867)
	at org.jetbrains.android.sdk.AndroidTargetData.getAllAttrDefs(AndroidTargetData.java:96)
	at org.jetbrains.android.sdk.AndroidTargetData.getPublicAttrDefs(AndroidTargetData.java:86)
	at org.jetbrains.android.resourceManagers.SystemResourceManager.getAttributeDefinitions(SystemResourceManager.java:89)
	at org.jetbrains.android.dom.AndroidDomExtender.registerExtensionsForManifest(AndroidDomExtender.java:579)
	at org.jetbrains.android.dom.AndroidDomExtender.processAttrsAndSubtags(AndroidDomExtender.java:627)
	at org.jetbrains.android.dom.AndroidDomExtender.registerExtensions(AndroidDomExtender.java:836)
	at org.jetbrains.android.dom.AndroidDomExtender.registerExtensions(AndroidDomExtender.java:75)
	at com.intellij.util.xml.reflect.DomExtenderEP.extend(DomExtenderEP.java:62)
	at com.intellij.util.xml.impl.DynamicGenericInfo.runDomExtenders(DynamicGenericInfo.java:164)
	at com.intellij.util.xml.impl.DynamicGenericInfo.access$000(DynamicGenericInfo.java:49)
	at com.intellij.util.xml.impl.DynamicGenericInfo$1.compute(DynamicGenericInfo.java:84)
	at com.intellij.util.xml.impl.DynamicGenericInfo$1.compute(DynamicGenericInfo.java:81)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.util.xml.impl.DynamicGenericInfo.checkInitialized(DynamicGenericInfo.java:81)
	at com.intellij.util.xml.impl.DynamicGenericInfo.getFixedChildrenDescriptions(DynamicGenericInfo.java:220)
	at com.intellij.util.xml.impl.DomSemContributor$3.fun(DomSemContributor.java:102)
	at com.intellij.util.xml.impl.DomSemContributor$3.fun(DomSemContributor.java:91)
	at com.intellij.semantic.SemServiceImpl$6$1.fun(SemServiceImpl.java:129)
	at com.intellij.semantic.SemServiceImpl$6$1.fun(SemServiceImpl.java:125)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:216)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:186)
	at com.intellij.semantic.SemService.getSemElement(SemService.java:37)
	at com.intellij.util.xml.impl.DomInvocationHandler.getFixedChild(DomInvocationHandler.java:644)
	at com.intellij.util.xml.impl.GetFixedChildInvocation.invoke(GetFixedChildInvocation.java:32)
	at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:689)
	at org.jetbrains.android.dom.manifest.Manifest$$EnhancerByCGLIB$$fe91717a.getApplication(<generated>)
	at com.android.tools.idea.model.ManifestInfo$4.compute(ManifestInfo.java:350)
	at com.android.tools.idea.model.ManifestInfo$4.compute(ManifestInfo.java:344)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.android.tools.idea.model.ManifestInfo.getApplicationComponents(ManifestInfo.java:344)
	at com.android.tools.idea.model.ManifestInfo.getActivities(ManifestInfo.java:308)
	at com.android.tools.idea.run.activity.DefaultActivityLocator$1.compute(DefaultActivityLocator.java:71)
	at com.android.tools.idea.run.activity.DefaultActivityLocator$1.compute(DefaultActivityLocator.java:68)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.android.tools.idea.run.activity.DefaultActivityLocator.computeDefaultActivity(DefaultActivityLocator.java:68)
	at com.android.tools.idea.run.activity.DefaultActivityLocator.validate(DefaultActivityLocator.java:56)
	at com.android.tools.idea.run.editor.DefaultActivityLaunch$State.checkConfiguration(DefaultActivityLaunch.java:47)
	at com.android.tools.idea.run.AndroidRunConfiguration.checkConfiguration(AndroidRunConfiguration.java:94)
	at com.android.tools.idea.run.AndroidRunConfigurationBase.validate(AndroidRunConfigurationBase.java:144)
	at com.android.tools.idea.run.AndroidRunConfigurationBase.checkConfiguration(AndroidRunConfigurationBase.java:87)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.checkSettings(RunnerAndConfigurationSettingsImpl.java:417)
	at com.intellij.execution.impl.RunManagerImpl.canRunConfiguration(RunManagerImpl.java:536)
	at com.intellij.execution.impl.RunManagerImpl.canRunConfiguration(RunManagerImpl.java:531)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:65)
	at com.intellij.execution.impl.ExecutionManagerImpl.start(ExecutionManagerImpl.java:396)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:61)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:384)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by chrissd23** [comment]
I think you should try to update your sdk-version from sdk manager.

**Comment by francisdb** [comment]
@GlennVM As I understood this has fixed itself so I'm closing this one.
